name: Deploy React App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    # Install dependencies
    - name: Install dependencies
      run: npm ci
    
    # Build the React app
    - name: Build React app
      run: npm run build
    
    # Deploy to Azure VM - Method 1: Copy build files directly
    - name: Copy build files to Azure VM
      uses: appleboy/scp-action@v0.1.5
      with:
        host: 52.229.166.212
        username: dinujaya
        password: v4cq#b~#aUcN~14F
        port: 22
        source: "build/*"
        target: "/var/www/html"
        strip_components: 1
        rm: true  # Remove existing files in target directory
    
    # Alternative Method 2: Deploy entire project and build on VM (requires Node.js on VM)
    # - name: Deploy entire project to Azure VM
    #   uses: appleboy/scp-action@v0.1.5
    #   with:
    #     host: 52.229.166.212
    #     username: dinujaya
    #     password: v4cq#b~#aUcN~14F
    #     port: 22
    #     source: "."
    #     target: "/var/www/html"
    #     rm: true
    
    # - name: Build on Azure VM
    #   uses: appleboy/ssh-action@v0.1.5
    #   with:
    #     host: 52.229.166.212
    #     username: dinujaya
    #     password: v4cq#b~#aUcN~14F
    #     port: 22
    #     script: |
    #       cd /var/www/html
    #       npm ci
    #       npm run build
